### ISSUE TITLE
What do we need to know about yarn.lock?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/meta#4]
So when Yarn came out, I read a couple of times that the `yarn.lock` file (which locks your dependency versions) should be ignored by library authors. That it should only be used by the "end" product (application for instance).

According to @thejameskyle, this is wrong. See [his tweet](https://twitter.com/thejameskyle/status/799005960270290944) and all the questions/answers.

Apparently, when a dependency has a `yarn.lock` file, it is being ignored if you run `yarn` on your project. So a dependency with a `yarn.lock` file will always get the latest versions of its own dependencies (making use of semver).

So far so good!

@sindresorhus, me and many others use [np](https://github.com/sindresorhus/np) to publish our modules. This tool runs a set of steps, one of them is to remove the `node_modules` folder and run `npm install` again to start off with a fresh `node_modules` directory. This also means that if a patch of a dependency was released, it will be downloaded and might brake the build because of a regression bug or something. 

If we would use `yarn` instead, in combination with `yarn.lock`, this will not be caught because that dependency version is fixed. The library gets published and people are starting to download the new version, which will break because of the regression. We could've caught this when we wanted to publish the module, but it didn't because of the lock file.

While I was typing this, I realised that this could always happen. If we publish our module first, and 5 minutes later a dependency is patched with a regression bug, it will also fail.

I just like to hear some peoples opinions on this. Give new insights. Apparently a lot of people have questions regarding this topic.

// @kevva @jfmengels @kentcdodds

**Comment by kentcdodds** [comment]
I appreciate being looped in because this is something I want to figure out as well. For the reasons you mention, I do `.gitignore` the `yarn.lock` on my open source modules (but not on my apps/workshops/etc.). But you make a good point:

> this could always happen. If we publish our module first, and 5 minutes later a dependency is patched with a regression bug, it will also fail.

Seems to me that using [greenkeeper.io](https://greenkeeper.io/) is the best solution. Unfortunately it does not currently support updating the yarn file (https://github.com/greenkeeperio/greenkeeper/issues/314), but I think that it could still useful.

In any case, I don't really see the drawbacks of gitignoring the `yarn.lock` file on open source modules. When what you want is the same version of dependencies that your users will be downloading, having a fresh `node_modules` every time someone clones seems like a good thing, then getting the offline/fast/secure capabilities of yarn thereafter is nice to have...

I definitely have an open mind here. Curious what others have to say.

**Comment by jamiebuilds** [comment]
Just to update, I'm writing a really long blog post about this topic that I'm going to post on the Yarn blog.

**Comment by ghost** [comment]
I assume this is the blog post - https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all

**Comment by ghost** [comment]
> When what you want is the same version of dependencies that your users will be downloading

If your users are using `yarn.lock` files in their applications, they won't have a _fresh_ `node_modules` every time (Assuming you mean _fresh_ in the sense that they get the latest possible version allowed by the semver ranges in `package.json`)

> In any case, I don't really see the drawbacks of gitignoring the yarn.lock file on open source modules

If I were to contribute to any of your projects, I would like to know that I can install your project's dependencies, and build successfully on the first try. Impeding my ability to contribute to one of your projects because one of your project's dependency introduced a breaking change, sounds like a drawback.

**Comment by ghost** [comment]
Also, there's a more detailed discussion on whether to check-in a Yarn lockfile here yarnpkg/yarn#1067
