### ISSUE TITLE
Intent to stop using `null` in my JS code

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meta#7]
I intend to stop using `null` in my code, in favor of `undefined`. There are many reasons for doing so.

**Feedback wanted**

Tweet: https://twitter.com/sindresorhus/status/1114894287387258886

## Background

http://2ality.com/2013/05/history-undefined.html

## Reasons

- Everyone uses `null` and `undefined` inconsistently and interchangeably.
- Nobody really knows when to use which.
- Supporting both `null` and `undefined` complicates input validation.
- Newer JS features like default parameters only work with `undefined`.
- `typeof null === 'object'`.
- I strongly believe it was a mistake to have two have both `null` and `undefined`.
- Using `null` makes TypeScript types more verbose: `type A = {foo?: string | null}` vs `type A = {foo?: string}`.

## Problems

- We cannot remove `null` from JavaScript

True, but we *can* pretend it doesn't exist (in most cases). And we can enforce no `null` usage with linters.

- We cannot change browser and Node.js APIs that accept/return `null`.

That's fine. At least we can improve user-land code.

- JSON doesn't support `undefined`

We just have to live with that. We could implement a custom JSON.parse/stringify that handles the conversion.

## Resources

- https://medium.com/@oleg008/what-if-we-stop-using-null-d705302b545e
- [TSLint rule to disallow `null`](https://palantir.github.io/tslint/rules/no-null-keyword/)
*(I intend to enforce this when `typescript-eslint` ports this rule)*
- https://stackoverflow.com/questions/36201110/why-do-functions-return-undefined-instead-of-null-by-default
- https://github.com/DavidBruant/ECMAScript-regrets/issues/26
- https://twitter.com/brendaneich/status/617450289889607681?lang=en
- https://twitter.com/brendaneich/status/330775086208524288

**Comment by niwox** [comment]
Other resource I found about this topic :
- Douglas Crockford thinks [`null` is a bad idea](https://www.youtube.com/watch?v=PSGEjv3Tqo0&feature=youtu.be&t=9m21s) and we should all just use `undefined`.

**Comment by jsynowiec** [comment]
Something can be defined, but allowed to be null (see it as a “no value” state). It’s different than just undefined. Especially with TypeScript and you’re even mentioning it a bit in the last point. 

> Using null makes TypeScript types more verbose: `type A = {foo?: string | null}` vs `type A = {foo?: string}`.

`foo: string | null` has different meaning and use than `foo?: string`

I’m interested in your reasoning about this difference. Don’t you encounter cases when you can benefit from it?

**Comment by atesgoral** [comment]
Since `let` got introduced, I started using `null` to give a dummy value to my variables, just because `let something;` reads like an unfinished sentence:

```
let x; // let x what?
```

```
let x = null; // oh so, we'll set it to something better later
```

The reason I don't use `let x = undefined;` is, well, it's functionally the same as just `let x;`, and only human-grammatically different. I find initialization to `null` to be a more explicit way of saying, "this is an explicit promise to set this value later."

**Comment by eps1lon** [comment]
> Feedback wanted

Don't know if you care about what other libraries do but React's ref objects for instance are declared as `type Ref<T> = { current: null | T }`. `null` is used here as the default value i.e. `React.useRef().current === null`.


> type A = {foo?: string | null}

Using `null` as the bottom value might be interesting if you care about property existence. If you declare `{ foo?: string }` you don't know if the value of `foo` might be `undefined` or if the the object doesn't have a property `foo`. If you want to explicitly communicate via types that property `foo` exists and might have a bottom value then `null` is kind of your only option

**Comment by joakimbeng** [comment]
How do you reason about `null`s in a database when used together with JS? E.g. an SQL database. Do you propose that undefined is translated to and from null when writing to/reading from the database?

**Comment by paulmillr** [comment]
Screw null and undefined, we should just switch to `Maybe` monad. 🤗

**Comment by yannbertrand** [comment]
I tend to use `undefined` as an unknown state e.g. when waiting for an HTTP response. 

I have been using `null` as an unset value e.g. a not-filled input but I never feel the need to use it as I could be using an empty string in most cases instead.

**Comment by felixfbecker** [comment]
A couple of thoughts:

> JSON doesn't support undefined

It does for properties: `JSON.parse(JSON.stringify({ foo: undefined })).foo === undefined`.
It only doesn't for array elements, but in all my time writing JS/TS I've never encountered a use case for JSON arrays with holes.

Another point: Many of the modern JS APIs return `undefined` for "doesn't exist", e.g. `array.find()`.

I'm personally not super strict with not using `null`, when working with the DOM API for example I use `null` because that's what DOM APIs return, and when working with databases the distinction between a `null` value and an _unknown_ value (i.e. wasn't `SELECT`ed) can be useful. But in general, I prefer `undefined`. Especially with TypeScript it saves a lot of boilerplate code.

**Comment by igghera** [comment]
I quit using null more than an year ago and i never felt the need for it.

**Comment by ricardohbin** [comment]
About this custom `JSON.stringify/JSON.parse`:

The main problem with currently `undefined` fields disappears in actual scenario is when a JS service needs to provide/receive JSON code to other languages - and all of them supports "null", not "undefined".

For example, if the custom converter works like:
```
JSON.parse(JSON.stringify({a: undefined})) // {a: undefined}
```
It will only works in js world. This is a problem when working principally in backend between a lot of services with different languages.

To custom `JSON.parse`, you can do an override `null` to `undefined` like python does with `None`, but to `JSON.stringify`, we need to make sure `undefined` turns in `null`.

Ex:
```
JSON.stringify({a: undefined}) // '{"a":null}'
JSON.parse('{"a":null}') // {a: undefined}
```

Makes sense?

**Comment by mcmire** [comment]
I'm curious why you're choosing to use `undefined` over `null`? To me, `null` is a more meaningful value than `undefined`. If something is `undefined`, then it's not set yet. But why should that be possible? Everything should be initialized to *something*, even if it's nothing. And if I want to initialize something to nothing, then `null` seems like the more semantic option of the two. 

Or is this less about semantics and more about pragmatism?

**Comment by medikoo** [comment]
To me it looks more as a TypeScript problem, that put you in that weird corner.

In 99.999% of validation cases, treating both `null` and `undefined` same way as _no value_, is what what will work perfectly. If TypeScript makes that difficult, then it's a problem to be addressed there.

**Comment by ljharb** [comment]
I don’t think it matters what you use in your own code - what matters is that you treat null and undefined the same as input.

Also, the cost of needing custom JSON tooling seems pretty understated.

**Comment by PazzaVlad** [comment]
I switched to use only undefined when it's possible about half a year ago. Never regret it.

**Comment by MarkTiedemann** [comment]
I only used `undefined` for a while. But I'm back to using both now. I find that worrying about this kind of consistency was impacting my productivity more than any supposed gains. Sometimes, I think it's best to accept that the world is messy...

Or ditch both `null` and `undefined`, and use `void 0` instead.

**Comment by nzxcr** [comment]
I use both. Null is explicit whilst undefined is implicit absence of a value. I care a lot about semantics because, well, code has two audiences, machines and developers; targeting one doesn't get you very far.

Having said that, I see no issues with just using undefined, even with JSON. If a property has a value of undefined, then don't send it.

**Comment by AaronFriel** [comment]
The only good use of null is in merge semantics over objects I think. Null means delete, whereas a stringified undefined key is absent meaning no change.

So I would say that maybe for your "is" and "ow" libraries it would be useful to keep null around, merge/PATCH semantics depend on it.

For other libraries if there is no distinction between "absent" and "deleted", use undefined.

For the rare case where "absent" and "deleted" are distinct values (do any of your libs do that?) I would keep null around instead of defining a symbol because it matches PATCH semantics and means your functions can be plugged into data transforming logic without change.

**Comment by BenoitRanque** [comment]
Regarding this being true:
```
JSON.parse(JSON.stringify({ foo: undefined })).foo === undefined
```
I would like to add that the following is also true:
```
JSON.parse(JSON.stringify({ foo: undefined })).bar === undefined
```
The JSON representation of `{ foo: null }` is `{ "foo": null }`
The JSON representation of `{ foo: undefined }` is `{}`

Using  null at least we know  the property exists.

If anything do not use undefined, which is what you don't have in statistically typed languages as they won't let you access properties of objects that don't exists.

**Comment by fvilers** [comment]
A lot of people has already said it, but to me, null is different than undefined. I use `undefined` to specify that a variable is, hmm, undefined. But I use `null` to specify that a variable *is* defined, but, currently, it's value is not usable, aka null.

As function parameters, having a distinction between undefined (the parameter has not been provided) and null (the parameter has been provided but should not be used) could be useful.

**Comment by SpeedoPasanen** [comment]
Coming from a relational DB background, I agree with the other Null defenders. Null definately has it's use cases and a distinct meaning. I only use undefined to strip useless properties before JSON encoding eg. for an API call.

**Comment by caesarsol** [comment]
I probably will change my mind after following this thread, but I have always used `null` in my code as much as possible, and always treat `undefined` as an indication something was wrong.

I think JS should trigger an error instead of making `undefined` appear... 
Always hoped for the [strong mode](https://groups.google.com/forum/#!msg/strengthen-js/ojj3TDxbHpQ/5ENNAiUzEgAJ) to land in actual browsers.

And to tell the truth, `undefined` is such an ugly word to write! :)

**Comment by mrchief** [comment]
> I strongly believe it was a mistake to have two have both null and undefined.

Agree 100%. 

> Newer JS features like default parameters only work with undefined.

This and the extra verbosity are good reasons to stop using it. 

> - Everyone uses null and undefined inconsistently and interchangeably.
> - Nobody really knows when to use which.
> - Supporting both null and undefined complicates input validation.

Cost of fixing or ensuring consistency for these points is also highly understated. :)

**Comment by JustinLivi** [comment]
I think the number of comments here and the wide range of responses indicate that there's probably no right or wrong answer here, similar to most coding style decisions. I think more important here than the final decision is coming up with a general guideline or rational.

That could take the form of an FAQ:

- What does the presence of `undefined` mean in your code? Does it imply that the value is optional, a placeholder, was removed, etc.?
- If `null` values will stick around, what do those represent? Is there any overlap in representation with `undefined`?
- How should the presence of `null` or `undefined` values in third party integrations be handled? Should they be handled via the conventions of the third party? Should some interface be maintained? Should a best-effort be made on a case-by-case  basis to translate third party conventions to whatever convention you decide on?

**Comment by GeoffreyBooth** [comment]
So CoffeeScript has something it calls the [existential operator](https://coffeescript.org/#existential-operator):

| CoffeeScript: | JavaScript:        |
|---------------|--------------------|
| `obj.prop?`   | `obj.prop != null` |

It takes advantage of the loose comparison operator `!=` or `==` to compare against `null`, because this way `null` and `undefined` are interchangeable. In the code above, `obj.prop?` will evaluate as false if `prop` is _either_ `null` or `undefined`.

I’ve copied this technique in JavaScript to basically treat `null` and `undefined` as interchangeable when evaluating input:

```js
if (input.prop != null) {
  // input.prop can’t be null or undefined, but can be false or 0 or an empty string
  doSomethingWith(input.prop);
}
```

This requires a flexible linter and a willingness to using one Bad Part (the loose equality operator) to hide another Bad Part (the existence of both `null` and `undefined`). I haven’t tested much, but it seems that `input.prop != undefined` should work just as well if your goal is to pretend that `null` doesn’t exist.

**Comment by ljharb** [comment]
The only difference there is that null is a keyword and undefined an identifier, which is why == null is generally preferred.

**Comment by ExE-Boss** [comment]
**WebAssembly** has resolved to use **ECMAScript’s** `null` as the equivalent of **WebAssembly’s** `nullptr`, once `anyref` is implemented: https://github.com/WebAssembly/reference-types/issues/9#issuecomment-380252992.

**Comment by astoilkov** [comment]
I have been thinking a lot about this. I did give thumbs up on this issue but I am starting to think the world isn't that perfect. Let me explain why:

- If all @sindresorhus modules are accepting `undefined` as their input this will mean other users would need to do some unpleasant stuff to make it work when they have `null` as a value in TypeScript. As pleasant as it would be to say people should start using only `undefined` there are teams that would never agree on that.
- JavaScript API doesn't agree on this rule. What happens when one of your libraries accepts only `undefined` but the JavaScript API actually returns `null`. `document.querySelector()` returns `null`. Or this will be an exception? Both aren't very pleasant.
- I found a slight benefit of using `null` in some use cases. Look at the example below:

```
// this is a world case example from our own app:

interface IState {
  dropLocation: string | null
}

function getDefaultState(): IState {
  return {
    dropLocation: null
  }
}
```

If the type `dropLocation` is instead `string | undefined` this would allow you to skip the `dropLocation` declaration. This at first seems good right (less typing)? However, verbose code and fewer rules wins it for me. Verbose is good because you don't need to go to `IState` definition to see what things are part of the state. Fewer rules because you don't need to decide whether you should add `dropLocation: undefined` or not. That also means that every developer on the project won't need to go through the same thinking process.

I really like fewer rules like the intent to stop using `null` but I believe that when removing a rule creates other rules this maybe isn't a good candidate for removal.

I would love to get feedback on this. I hope your judgment won't be affected because I didn't include the benefits of using only `undefined` – I love the idea, I actually hope I am wrong with this.

**Comment by ExE-Boss** [comment]
Also, `undefined` as a global constant doesn’t actually exist before ES5, and still behaves weirdly in non‑strict mode.

Also, the following aren’t equivalent:
```ts
interface IState {
	// A required `dropLocation` property, that can be a `string` or `undefined`.
	dropLocation: string | undefined;
}
```

```ts
interface IState {
	// An optional `dropLocation` property, that can be omitted, a `string` or `undefined`.
	dropLocation?: string;
}
```

**Comment by sindresorhus** [comment]
Validated:

<img width="597" alt="Brendan Eich - Use Undefined -Screenshot 2019-09-09 at 23 36 31" src="https://user-images.githubusercontent.com/170270/64861309-cd852800-d659-11e9-9c66-92957ad68216.png">

https://twitter.com/BrendanEich/status/1171079812179361792

**Comment by SamHH** [comment]
@ExE-Boss That distinction doesn't exist in TypeScript - there is no distinction in the type system being an undefined value and a missing key. See [here](https://github.com/microsoft/TypeScript/issues/13195).

It's for this reason that, when I can't use the likes of the Maybe/Option monad, I choose to use null instead - it's more explicit that I've actively set something to be "empty" rather than undefined which can pop up by itself in the absence of a value.

**Comment by jhnns** [comment]
If anyone is interested, these are my two cents :)

---

In my experience it's problematic when developers start to use both to represent the absence of a value. When a value can either be `null` or `undefined` or something else, people start to write code like this:

```js
if (someValue) {
```

This is problematic because it may introduce bugs where `someValue` is casted implicitly to `false` (e.g. with `0` or `""`). The alternative would be to use:

```js
if (someValue == null) {
```

which conflicts with our rule to use strict equality checks. It's also not intuitive that `== null` will also check for `undefined`. The biggest problem to me is that `== null` is also not optimizable for the browser because `document.all == null` might also evaluate to `true` (this is a little known fact).

The last alternative would be to write:

```js
if (someValue === undefined || someValue === null)
```

which is just annoying.

**But there are more problems.** JS default parameters for functions and destructuring will only work with `undefined`. This makes it even more complicated if the codebase is mixing `undefined` and `null`. On the other hand, `JSON.stringify` will just omit `undefined` values.

**A codebase cannot ignore these issues in my experience. It should stick to a guideline.**

### Comparison

#### Pro `undefined`

- Function default parameters only work with `undefined`
- Destructuring with default values only work with `undefined`
- `typeof "object"` works as intended
- Arithmetic with non-existent values produces expected results:
   - `2 + null; // 2`
   - `2 + undefined; // NaN`

#### Pro `null`

- JSONs can only contain `null`
- React components can only return `null` for rendering nothing (`undefined` is not supported)
- DOM APIs often use `null`
- Functions can distinguish between implicit `return` and `return null` (although it's not a good style to mix both in the same function)
- Distinguishing between a non-existent object property and a null property is straightforward:
	- `obj.prop === undefined` means it doesn't exist
	- `obj.prop === null` means it exists but it's not set

### My conclusion

For a long time (especially pre-ES2015) I was pro `null` because setting something to `null` explicitly was a clear sign that "there is something, it's just not set". It maps clearly to the concept of known knowns, known unknowns (`null`) and unknown unknowns (`undefined`).

However, with the rise of ES2015 and the widespread use of default parameters and values, the usability problems became more apparent. In one of our projects we had to do something like this just to use default props:

```js
<SomeComponent
   a={model.a === null ? undefined : model.a}
   b={model.b === null ? undefined : model.b}
   c={model.c === null ? undefined : model.c}
/>
```

Since this is too much code to write and read, people will either deviate from the rule to use `null` and use `undefined` where it's easier for them (eventually leading to the situation I mentioned at the beginning) or use unsafe boolean expressions like:

```js
<SomeComponent
   a={model.a || undefined}
   b={model.b || undefined}
   c={model.c || undefined}
/>
```

[Nullish Coalescing](https://github.com/tc39/proposal-nullish-coalescing) will make that less error prone, but it's still unnecessary code in my opinion.

So my proposal would be to ban `null` and only use `undefined`. The [`eslint-plugin-no-null`](https://www.npmjs.com/package/eslint-plugin-no-null) rule could enforce that.

For situations where developers need to use `null` (e.g. when returning nothing from React components) we can still have a single module that exports a `null` value:

```js
// eslint-disable-next-line no-null/no-null
const NULL = null;
export default NULL;
```

For situations where developers need to save `undefined` to a JSON it's possible to have a utility function that converts all explicit `undefined` properties into `null` before sending it to `JSON.stringify()`. For consistency reasons you would also need the opposite for `JSON.parse()`.

**Comment by fregante** [comment]
> React components can only return null for rendering nothing

I’m not totally familiar with React but in JSX this renders an empty element: `<a>{undefined}</a>`

> Functions can distinguish between implicit return and return null

How is this a pro?

> Distinguishing between a non-existent object property and a null property is straightforward

I think you can detect an existing but `undefined` property with `key in obj`

**Comment by ducin** [comment]
> Something can be defined, but allowed to be null (see it as a "no value" state). It’s different than just undefined. Especially with TypeScript and you’re even mentioning it a bit in the last point.
> 
> > Using null makes TypeScript types more verbose: `type A = {foo?: string | null}` vs `type A = {foo?: string}`.
> 
> `foo: string | null` has different meaning and use than `foo?: string`
> 
> I’m interested in your thoughts about this difference. Don’t you encounter cases when you can benefit from it?

According to your naming convention, `null` is a _no value_ thing, an explicit one. Another _no value_ being `undefined`, but an implicit one, is just redundant. It's clearly _accidental complexity_ to have two different _no values_.

**Comment by alexilyaev** [comment]
If you're interested in which DOM API's specifically can return `null`...
Search for `null` in these documents:

- [TypeScript - lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts)
- [W3 DOM Spec](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-1950641247)

**Comment by ibraheemdev** [comment]
What about external libraries? While it might be a good idea to stop using null in your own code, you should probably still make it a habit to check for both null and undefined to avoid problems with external code.
> we cannot remove null from JavaScript, but we can pretend it doesn't exist

Even if it does become general convention to not use null, as a developer, you cannot depend on that convention and skip null checks in favor of undefined, because null is deeply engrained into the language itself.

So... we can't really pretend that it doesn't exist

**Comment by dr-js** [comment]
If we just set the JSON and historical API thing aside, I think now with `Symbol` we could use something like:
```js
const NULL_NUMBER = Symbol('null number')
const NULL_STRING = Symbol('null string')
const NULL_OBJECT = Symbol('null object')
```
to get `null` with type info baked in.
And most of the time we do know and check the type.

**Comment by BitpopCoin** [comment]
Null is intentionally set to mean empty

Undefined is the default meaning it's probably waiting

They're both important, you can't claim

**Comment by fregante** [comment]
> check for both null and undefined to avoid problems with external code

It depends on the occasion, certainly, but you can very well only accept `undefined` and not `null`, just like your function doesn't accept certain other types. If you call an API with the wrong type, you're using the API wrong and that's how you get TypeErrors

**Comment by fregante** [comment]
> Null is intentionally set to mean empty. I set an undefined variable to null.

Unless you accepts a wide range of types _except null_, you can probably still avoid using `null` by using `0`, `-1`, `false`, `{}` or `undefined` itself, because `{hello: undefined}` is still different from `{}`.
The emptiness in this case can be checked with `'hello' in {} === false`

**Comment by tonycassara** [comment]
What happens if a 3rd party API provides a fallback value of `null`? That's the only reason I haven't stopped using it.

**Comment by benjamingr** [comment]
Hey Sindre, this is "trending" in hacker news in case you're wondering why a year old issue is suddenly getting attention. 

https://news.ycombinator.com/item?id=24956156

**Comment by symbioquine** [comment]
I don't have a strong opinion, but there are a few arguments which don't seem to have been presented yet;

* "null" less than half as long as "undefined" and can be typed one handed if you use QWERTY. Even the first four letters require fewer finger movements since two of the letters are the same.
* `null` as a keyword for a missing no-value reference seem to be more common across languages than "undefined".

**Comment by Indomitable** [comment]
Actually my opinion is exactly opposite: To stop using `undefined` and to use only `null`. For me undefined in more like system type while null is more user type. `undefined` has double meaning, the check `type obj.x === 'undefined'` it maybe the `x` prop is missing or `x` prop is available with value `undefined`. `Object.keys` will return different results in both cases. It is possible to code without using the word `undefined`. So when I do a code review I always encourage devs to replace `undefined` with null.

**Comment by Indomitable** [comment]
Imagine you are writing a library and you expose an interface 
```ts
interface ISomething {
  param?: string;
}
```
Then this library is consumed from by another dev, who see, that param is an optional property so he decides to use
`'param' in obj` where obj is ISomething. If in your library you assign `undefined` to the `param` then the consumers may have bug, because `'param' in obj` will be `true`. 
So don't forget there is a huge difference between 
```ts
interface ISomething0 {
   param?: string
}
interface ISomething1 {
   param: T | undefined;
}
interface ISomething2 {
  param: T | null;
}
// Sometimes i see even: 
interface ISomething3 {
  param?: T | null | undefined;
}
```
I would never use `ISomething1` or `ISomething3` declaration, unfortunately TS doesn't make a lot of difference between 0 and 1. 
Here is another example of using `undefined` which can cause problems: Optional parameters in functions. Many JS libraries use `arguments` in functions to create overloads. there is a lot of JS code that look like:
```js
function do(param0, param1?, param2?)  {
     switch(arguments.length) {
        case 1:  {
             // use only param0
        },
        case 2: {
           // use param0 and param1
        },
        case 3: {
           // use param 0, param 1 and param2
        }      
}
```
A developer who  is used to use `undefined` as NO VALUE, may invoke function like `do(1, undefined, '2)` which immediately will bring bug in his code.

**Comment by Indomitable** [comment]
functions like `Array.prototype.find` return `undefined` which means there is no value found. What if you have code like: `[1, 2, undefined, 0].find(x => !x)`  your code will return `undefined` you may assume there are no Falsy values in your array but it is quite opposite: you have 2 of them `undefiend` and `0`

**Comment by lafiosca** [comment]
@Indomitable Your several examples here feel contrived and seem to indicate anti-patterns to me.

First, regarding the library exporting the `ISomething` interface, given that we're in the realm of TypeScript, I contend that the developer using `'param' in obj` to check for the type of `obj.param` is in the wrong. If I write TypeScript code like that, it won't work:

```ts
interface OtherThing {
    a: number;
    b?: number;
}

const getDoubled = (e: OtherThing) => {
    if ('b' in e) {
        return e.b * 2;
    }
    return e.a * 2;
}
```

Specifically, TS will highlight an error on the `e.b`: `Object is possibly 'undefined'. (2532)`. The existence of the property b does not imply that it is not `undefined`. (Now if you're arguing that we should not use undefined because you disagree with this aspect of TypeScript's semantics, that's perhaps a separate issue.)

As a side note, in contexts not involving object literals directly, TS interfaces only specify the minimal subset of properties. Other keys you might not expect can be "in" an `OtherThing`. For example:

```
const x = { a: 3, b: 5, c: 'extra' };
const y = getDoubled(x); // this is fine
console.log('c' in x); // outputs true
```

In your next example you say there is a huge difference between `ISomething0` and `ISomething1` but that TS doesn't make a big difference between them. I'm not sure what you mean by this. In my experience, TS treats these quite differently. For example:

```
interface Something0 {
   param?: string
}

interface Something1 {
   param: string | undefined;
}

const a0: Something0 = { param: undefined }; // this is fine
const b0: Something0 = {}; // this is fine

const a1: Something1 = { param: undefined }; // this is fine
const b1: Something1 = {}; // TS complains
```

TS will complain about `b1` with this error: `Property 'param' is missing in type '{}' but required in type 'Something1'. (2741)`

Regarding your third example about the variadic function breaking when `undefined` is passed explicitly as a middle argument to a library function, it seems like this would be a mistake in the implementation or documentation of the library, or a mistake in the usage of the library. It's not clear to me from the example what specific bad behavior you're anticipating here, nor how it implies we should not use `undefined`.

Regarding your final example, you are correct, although again it feels very contrived to me. As a developer I need to be aware that the standard implementation of `Array.find` returns `undefined` when the item is not found, I need to be cognizant of whether the data might contain `undefined` values, and probably I should be using something like `Array.findIndex` instead for cases like this. But we would have run into a conflict like this regardless of what value the implementation used to indicate a missing element simply because JS arrays can contain elements of any type. In other words, if they had decided that `Array.find` would return `false` when an item was not found, then I would have run into this issue with any array containing `false` as an element. (If this became a serious enough issue for me, I would consider creating a new `find` method which returned a composite object indicating whether the item was found or not and including the value when it was found.) I do not feel like this is a compelling reason to prefer using `null` over `undefined` in most of my code, particularly because this exact issue could still come up when consuming an array which I did not construct, from another source such as a library.

Now for the full disclosure of where I'm coming from here...

I'm primarily a TypeScript developer right now. Perhaps about a year ago, I found this thread and the discussion around it, and my immediate reaction was "NO, `undefined` and `null` have very distinct, albeit subtle, meanings! I use them both depending on context!" But I read the various arguments and decided, "Ok, I'll give this a shot for a bit, as an experiment, and see how I feel about it." I stopped using `null` in my own TS code (other than when JSON/APIs are involved), and I have to admit I have not missed it at all. In particular, `undefined` is a lot friendlier with TypeScript code than `null` is, for the reason that it's used implicitly with TS's optional values. I have not run into a single contrived scenario where I felt hamstrung by this decision in a year of writing TypeScript every day, including front-end code (React Native mobile and React web), back-end code (Lambda/Express REST API services using SQL databases), open-source libraries for public consumption as modules, and various side projects.

I've remained subscribed to this issue since then, to see if anyone came along with more compelling arguments (in either direction), and it's been pretty amusing to see the sudden burst of activity. With the barrage of gut disagreements coming in, I wanted to chime in from the perspective of someone who really appreciated @sindresorhus bringing up this suggestion and has found it valuable in their own work. Thank you.

**Comment by fregante** [comment]
> functions like `Array.prototype.find` return `undefined` which means there is no value found. What if you have code like: `[1, 2, undefined, 0].find(x => !x)` your code will return `undefined` you may assume there are no Falsy values in your array but it is quite opposite: you have 2 of them `undefiend` and `0`

Looks like a classic example of "but this one weird case" that nobody really needs. **Why would you need to find `undefined` in an array?**

**Comment by Indomitable** [comment]
First I think the high activity is due to the recent publication in "Hacker News". 
When I have 
```
interface X {
    p?: string;
}

const v : X = { 
    p: undefined
};
```
I have problem with Typescript, because this shouldn't be allowed, in this case `p` is optional prop, not a prop that can contain `undefined`, if I wanted otherwise I would write:
```
interface X {
    p: string | undefined;
}
```
I really don't like that `undefined` has two meanings: 1: missing property and 2 no value. 

@fregante This is just an example and in this case I search for the first "Falsy" value, not if there is value or not. By returning `undefined` I can not figure it out is `undefined` in the array or there are no "Falsy" values.

**Comment by fregante** [comment]
> @fregante This is just an example and in this case I search for the first "Falsy" value, not if there is value or not. By returning `undefined` I can not figure it out is `undefined` in the array or there are no "Falsy" values.

Whichever nullish value you prefer, unless you can ensure that only one exists, you need account for both either way. The first solution that comes to mind is by using `findIndex` instead of `find`.
